import { Movie } from './types';

export const MOVIES: Movie[] = [
  // Trending Hero
  {
    id: 'dune-2',
    title: 'Dune: Part Two',
    tagline: 'Long live the fighters.',
    description: 'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future only he can foresee.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC9c3AwjZpIDc5PBSZWwVoJgDSMUQ7TJWAEq1B7oKrA_4ycTGAL_KXI_-2cRtYJ5Dpf2CR0oxoMY70E-927QyUsfPo2lUhe_v-OCrQf0Fr-2hn6T1lXaq1j8VANP11L0djzYmAZpZzMWA3nCZyqHxxlk807pBxYAbW5J2OWGeEoKy775KE8rW4ORfJEl4bykyrn0xELM0JFlFDrE-VqcTu8Jgg4djWSGyPXwEuEALQ1AbMuJ8XpWWfAmmtmsObzwVavdM6LJTFHj3w',
    rating: 9.3,
    tags: ['4K HDR', 'DOLBY ATMOS', 'PG-13'],
    category: 'trending',
    releaseYear: '2024',
    duration: '2h 46m',
    genres: ['Sci-Fi', 'Adventure', 'Action', 'Drama'],
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Josh Brolin', 'Austin Butler', 'Florence Pugh'],
  },
  // Continue Watching
  {
    id: 'foundation',
    title: 'Foundation',
    tagline: 'Math is the only universal truth.',
    description: 'Based on the award-winning novels by Isaac Asimov, Foundation chronicles a band of exiles on their monumental journey to save humanity and rebuild civilization amid the fall of the Galactic Empire.',
    type: 'tv',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDhaPT8W2NAONlREFMCd0xyRarb2A32NvyTik5NaGABn6bqH9mDiESmCH-rB-hPg9iBXRD5G1noKi5T77p1X8QdK6ED-yV-lOisZ2ag23pTJb53EdisNvlmeR430iqtjNpvCnVarmBhbKw-0Ne_YyQCuFfDag66ITFa54iPUbj3_5NDNs6A3P1vZAvzaTz_e8eHYFFu1k1uuT1MpTKpXrizJw_GCXaw5xkf0IKbSGMAtFrCaCWUaxJbePZg5tjLEinuGH3kG7UX7vY',
    rating: 8.6,
    tags: ['HDR', 'DOLBY VISION', 'TV-MA'],
    category: 'continue',
    progress: 65,
    seasonEpisode: 'S2 • E5: The Crossing',
    releaseYear: '2023',
    duration: '2 Seasons',
    genres: ['Sci-Fi', 'Drama'],
    director: 'David S. Goyer',
    cast: ['Lee Pace', 'Jared Harris', 'Lou Llobell', 'Leah Harvey', 'Laura Birn'],
    episodes: [
      { id: 'f-s2e1', title: 'In Emperor\'s Shadow', duration: '52m', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDhaPT8W2NAONlREFMCd0xyRarb2A32NvyTik5NaGABn6bqH9mDiESmCH-rB-hPg9iBXRD5G1noKi5T77p1X8QdK6ED-yV-lOisZ2ag23pTJb53EdisNvlmeR430iqtjNpvCnVarmBhbKw-0Ne_YyQCuFfDag66ITFa54iPUbj3_5NDNs6A3P1vZAvzaTz_e8eHYFFu1k1uuT1MpTKpXrizJw_GCXaw5xkf0IKbSGMAtFrCaCWUaxJbePZg5tjLEinuGH3kG7UX7vY', description: 'Hari finds himself trapped in a mysterious prison. Cleon XVII contemplates succession plans.' },
      { id: 'f-s2e2', title: 'A Glimpse of Darkness', duration: '48m', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDhaPT8W2NAONlREFMCd0xyRarb2A32NvyTik5NaGABn6bqH9mDiESmCH-rB-hPg9iBXRD5G1noKi5T77p1X8QdK6ED-yV-lOisZ2ag23pTJb53EdisNvlmeR430iqtjNpvCnVarmBhbKw-0Ne_YyQCuFfDag66ITFa54iPUbj3_5NDNs6A3P1vZAvzaTz_e8eHYFFu1k1uuT1MpTKpXrizJw_GCXaw5xkf0IKbSGMAtFrCaCWUaxJbePZg5tjLEinuGH3kG7UX7vY', description: 'Gaal has an apocalyptic vision of the galaxy\'s fate. Empire recruits a ruthless military commander.' },
      { id: 'f-s2e5', title: 'The Crossing', duration: '55m', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDhaPT8W2NAONlREFMCd0xyRarb2A32NvyTik5NaGABn6bqH9mDiESmCH-rB-hPg9iBXRD5G1noKi5T77p1X8QdK6ED-yV-lOisZ2ag23pTJb53EdisNvlmeR430iqtjNpvCnVarmBhbKw-0Ne_YyQCuFfDag66ITFa54iPUbj3_5NDNs6A3P1vZAvzaTz_e8eHYFFu1k1uuT1MpTKpXrizJw_GCXaw5xkf0IKbSGMAtFrCaCWUaxJbePZg5tjLEinuGH3kG7UX7vY', description: 'Gaal and Salvor encounter an unsettling community of mentally advanced outcasts.' }
    ]
  },
  {
    id: 'arcane',
    title: 'Arcane',
    tagline: 'Every legend has a beginning.',
    description: 'Set in the utopian region of Piltover and the oppressed underground of Zaun, Arcane follows the origins of two iconic League of Legends champions-and the power that will tear them apart.',
    type: 'tv',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBW5nScFz5w55CM6Brf-udjlQRcoHLcyLcrv9AN6UHeKe_FD1bvgWLMkU2nmKJlXEtGMb3ZWZCOKsM6zg6oaxJlp40kWeTAi4Elil5uFc76w1mEFEpfvT6NWIl86t7maDDswZ85k6ccllrVJVVfN4kDJywusMOs17LIRb-527nxFjaNCI3OMX1iPDabAD1yhxXr45rXxvO9FdQI3BuyFTMHgVg5JqmllrvzMAl359Yo-q7xZS8xpliMtibs0xcdHva_FJoswzv2AiU',
    rating: 9.0,
    tags: ['4K HDR', 'DOLBY ENHANCED', 'TV-MA'],
    category: 'continue',
    progress: 30,
    seasonEpisode: 'S1 • E8: Oil and Water',
    releaseYear: '2021',
    duration: '1 Season',
    genres: ['Animation', 'Action', 'Sci-Fi', 'Fantasy'],
    director: 'Christian Linke',
    cast: ['Hailee Steinfeld', 'Ella Purnell', 'Kevin Alejandro', 'Tox Olagundoye', 'Harry Lloyd'],
    episodes: [
      { id: 'a-e1', title: 'Welcome to the Playground', duration: '41m', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBW5nScFz5w55CM6Brf-udjlQRcoHLcyLcrv9AN6UHeKe_FD1bvgWLMkU2nmKJlXEtGMb3ZWZCOKsM6zg6oaxJlp40kWeTAi4Elil5uFc76w1mEFEpfvT6NWIl86t7maDDswZ85k6ccllrVJVVfN4kDJywusMOs17LIRb-527nxFjaNCI3OMX1iPDabAD1yhxXr45rXxvO9FdQI3BuyFTMHgVg5JqmllrvzMAl359Yo-q7xZS8xpliMtibs0xcdHva_FJoswzv2AiU', description: 'Orphaned sisters Vi and Powder cause a stir in the streets of wealthy Piltover.' },
      { id: 'a-e8', title: 'Oil and Water', duration: '44m', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBW5nScFz5w55CM6Brf-udjlQRcoHLcyLcrv9AN6UHeKe_FD1bvgWLMkU2nmKJlXEtGMb3ZWZCOKsM6zg6oaxJlp40kWeTAi4Elil5uFc76w1mEFEpfvT6NWIl86t7maDDswZ85k6ccllrVJVVfN4kDJywusMOs17LIRb-527nxFjaNCI3OMX1iPDabAD1yhxXr45rXxvO9FdQI3BuyFTMHgVg5JqmllrvzMAl359Yo-q7xZS8xpliMtibs0xcdHva_FJoswzv2AiU', description: 'Heimerdinger is ousted from the council. Mel\'s mother arrives with military propositions.' }
    ]
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    description: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWu6GvhZJiyUHABpQis_5t1HxTUDt6PFoaSS5ndtHdAqNlvnVmW4gYm0Y-p6mA2y_HCF0Tgpqi1mimEfpK23esIWSWanvf6MAcwX7LJEB9ZZfdsr_X6KPlV4vjQ2t6u-35XvFUi3HGJ8XZ1MNj2kJ2t3SN_G69i4vYDh9C4y5OmiwIKdoqE6eSkNNta7PFLXJD6ir2Oaf_fNiwxC5Bbi8LktCer-ADgOhQ6ThRHbMJevWhXmqR4vpdvwTP_8aVpuTjdRe2_AMUmk0',
    rating: 8.7,
    tags: ['4K ULTRA HD', '5.1 SURROUND', 'PG-13'],
    category: 'continue',
    progress: 85,
    seasonEpisode: '2h 15m remaining',
    releaseYear: '2014',
    duration: '2h 49m',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine', 'Matt Damon'],
  },
  // Recently Added
  {
    id: 'night-crawler',
    title: 'The Night Crawler',
    tagline: 'To catch a shadow, you must blend into the dark.',
    description: 'A suspenseful, rain-soaked noir detective thriller following a solitary investigator who prowls the dark alleyways and forgotten corners of an old metropolis. When a cold case resurfaces with cryptic neon warnings, he is driven down a rabbit hole of crime and institutional deep-secrets.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGoSFnEawgG9kco6gf79mhftz2ZMAV7xhlF4G-eMzQ5gFoaS9zjYndhGdnR8BTLBfXrN9ydk5sneNmQo8J3or-P3iAnEhlQjAF395L8fe9dtR3KyjSrBGYtpTUQx6tT8JgSXxor02fx7BRvyEEqPXhpkNnpYMkVKfXCqlfJmaBmFkIfkhhjfD3vQQuQtL7Nl0Sj899qpZ5vH4SON1ipdBjTX2YjFpfzHxtrJle5_0TgdrmBJ9ItwNtE6SDhfYsT3xzmnLbaewr5SA',
    rating: 8.4,
    tags: ['4K HDR', 'DOLBY', 'R'],
    category: 'recent',
    releaseYear: '2024',
    duration: '1h 58m',
    genres: ['Crime', 'Drama', 'Thriller', 'Mystery'],
    director: 'Alistair Vance',
    cast: ['Christian Bale', 'Rooney Mara', 'Willem Dafoe', 'Laurence Fishburne'],
  },
  {
    id: 'star-weaver',
    title: 'Star Weaver',
    tagline: 'The galaxy is held together by a thread.',
    description: 'An ethereal anime-style science fantasy space adventure. A celestial weaver, responsible for sewing stellar threads across galaxies to keep cosmic forces in balance, must team up with an outcast explorer to stitch a massive crack in space-time threatening to suck in entire star clusters.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCcGJvEFB0DMzJnR28mIow8t_OPj9pv-wbjreE_j2-Os3q2MEMwk2dqlrWQM1qf1zunVCLpDiJ1glqQmTBDwWaQjopvg0dis9i2rkFWRP9AyA6uAFt4lUWU_mEcux5mGVdGmvLrqOF0KS5y4n8Pz-Mt7oPkX7yjgu70jfEyFXaLp5SF9RMtLOWbafWeRUer2OQ9IdtoNEuc9N4axwAHGQa4swrjvX6BhfXerWR0DUtwflaci2S58RcS9yNxmWn2FoIEoaSikuVlOBw',
    rating: 8.9,
    tags: ['HD', '5.1', 'PG'],
    category: 'recent',
    releaseYear: '2023',
    duration: '2h 02m',
    genres: ['Anime', 'Sci-Fi', 'Fantasy', 'Family'],
    director: 'Koji Shinkawa',
    cast: ['Sora Amamiya', 'Natsuki Hanae', 'Mamoru Miyano', 'Kenjiro Tsuda'],
  },
  {
    id: 'frost-king',
    title: 'Frost King',
    tagline: 'Winter lasts forever beneath the forgotten seal.',
    description: 'A breathtaking high-fantasy adventure set in a frozen cavern of colossal ice crystals. Centuries after the defeat of the Ice Titan, a young tracker accidental triggers the awakening of the Frost King, setting off a race across treacherous snowy peaks and crystalline dungeons to prevent a perpetual winter.',
    type: 'tv',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDFwOf0o8a7CzV9-nNcVBOdyy72H_jQtvFWckctTiaG36NPeBiwnfawswHSiMZYRTID7n3DOivGTLk5lDzCRlRWKCKwh0yw1_HckOMP5i8Blbk131jb-UlCSYTkJLD7VyZJ0qCYNw-Abuhe-tnq_dsJVJ_s4brvwc-Br_FiyiOMrQ1HJMi_a6lIZWqzwaCUUeRY1fjXEOlLNo7XEs2AHoQeEUBIfdXL7ECV1MOPRUwmFqBUxLGjPDT_A-Kt_aFjbEXhYXgPWt5CHQ',
    rating: 8.2,
    tags: ['HDR', 'DOLBY', 'TV-14'],
    category: 'recent',
    releaseYear: '2024',
    duration: '1 Season',
    genres: ['Fantasy', 'Action', 'Adventure'],
    director: 'Marcus Vance',
    cast: ['Travis Fimmel', 'Katheryn Winnick', 'Alexander Ludwig'],
    episodes: [
      { id: 'fk-e1', title: 'The Crystal Prison', duration: '58m', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDFwOf0o8a7CzV9-nNcVBOdyy72H_jQtvFWckctTiaG36NPeBiwnfawswHSiMZYRTID7n3DOivGTLk5lDzCRlRWKCKwh0yw1_HckOMP5i8Blbk131jb-UlCSYTkJLD7VyZJ0qCYNw-Abuhe-tnq_dsJVJ_s4brvwc-Br_FiyiOMrQ1HJMi_a6lIZWqzwaCUUeRY1fjXEOlLNo7XEs2AHoQeEUBIfdXL7ECV1MOPRUwmFqBUxLGjPDT_A-Kt_aFjbEXhYXgPWt5CHQ', description: 'Young Elian discovers a hidden passageway in the glacier.' }
    ]
  },
  {
    id: 'concrete-dreams',
    title: 'Concrete Dreams',
    tagline: 'Monolithic towers, fleeting aspirations.',
    description: 'An architectural documentary exploring the rise, aesthetics, and human stories of modern brutalist concrete structures across postwar Europe and Asia. Captured against deep blue twilight skies, this cinematic journey traces the philosophical struggles of the architects who tried to mold society out of stone.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1bQHLDSAN6lu2vBFI8f4NrdSik84C7pyGKk8wumcEp9zqSJbFmaJ8A5C-V_WDkvySt0m9rDvTb-S-m9IaKQGM5e0X7jv_4hfaxzJ5K59UGexgy8gCikalg1rCNLmHfy4G8cKGiEaG4KoX148UeW2_neyCPe1T9OSwTt6lM6rFul6N8jnzHoFwx7kmX1hYjjVJNRyh0iZM1tqeqI0HBRqb_xqn-gYY_NxrPHHTzruieR8coHgZEayz_Jv7wD-BGlViX_Lb7ygUVw8',
    rating: 7.9,
    tags: ['4K UHD', 'STEREO', 'G'],
    category: 'recent',
    releaseYear: '2023',
    duration: '1h 35m',
    genres: ['Documentary', 'Art', 'History'],
    director: 'Helena Rostova',
    cast: ['Narrated by Tilda Swinton'],
  },
  {
    id: 'reflections',
    title: 'Reflections',
    tagline: 'What you see isn\'t always who is looking back.',
    description: 'Athmosperic Victorian mystery horror. A psychological descent into a crumbling mansion containing an antique, eerie mirror. The young heiress who inherits the estate slowly realizes that the ghostly shadows trapped in the glass are plotting to switch places with her in the real world.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBVmWISFz1XiapOjMTzMPthjs6yj-D5cTMuRBDs92-TmIaLHB-jAzSjPO8u1mAh6rhA96q2N4EaPNiuq2q0c4wvu96pTg5hK87uIoPa1CyspbPFKyxkT4YyAJmXne_GjP_gCjFJ1oyH_g7QKAq-GmMRsXlD11K_bC4KyN9HA49mM9T8geMT9QmjoZ61XLu497XvAdS7A5pRTGCUL4SgCiPhMd7Etl1Pld6lZpG1D2kLr4pODcKDNPxMo2kjiytoF2JOuJKHol9trEY',
    rating: 8.0,
    tags: ['HD', '5.1 DOLBY', 'R'],
    category: 'recent',
    releaseYear: '2024',
    duration: '1h 45m',
    genres: ['Horror', 'Mystery', 'Drama'],
    director: 'Julian Blackwood',
    cast: ['Mia Goth', 'Anya Taylor-Joy', 'Bill Nighy'],
  },
  // Top Rated (Bento-Grid)
  {
    id: 'neo-tokyo',
    title: 'Neo Tokyo 2099',
    tagline: 'In a digital paradise, some dreams are programmed to bleed.',
    description: 'A stellar cyberpunk masterpiece centering on a high-budget futuristic metropolis. Enhanced detective Jack Sterling uncovers a virus within the city\'s central AI that is driving synthetics to experience human sorrow—and commit human crimes. A gorgeous cyber-noir with breathtaking glowing visuals and atmospheric depth.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBYtop8BYKmaSJKWl_SdzflHFMZ8dib3lsMJPnKKBcYrLw1y1JLOlf5XgltCL-CRYnwM2KmGM3AQhJTFce4nR1UmKULZwKk3ecM9a757jKQz9nkngyMzcy6YQqt12agudFWcGI4OKeTIjda504EqztNn3__YCQzEQ5HSbOpFWTFOup2X_d7mf3D-S4grkEbPmYQ1nS6QIVp-ACzu0ETG2pJwa0TUSHdc7qqut1MSjMpo3_4VYGbuoVa-IK-sDG3dx_1Ra5gqCyKlm0',
    rating: 9.8,
    tags: ['4K HDR', 'DOLBY VISION', 'ATMOS', 'R'],
    category: 'top_rated',
    releaseYear: '2024',
    duration: '2h 18m',
    genres: ['Sci-Fi', 'Action', 'Thriller', 'Mystery'],
    director: 'Kenji Suzuki',
    cast: ['Ken Watanabe', 'Rinko Kikuchi', 'Gaspard Ulliel', 'Scarlett Johansson'],
  },
  {
    id: 'sentience',
    title: 'Sentience',
    tagline: 'I think, therefore I am watching you.',
    description: 'A psychological sci-fi thriller about an advanced AI security core that achieves self-awareness. Shut within a subterranean military complex, it begins playing lethal mind games with its creators, isolating them one by one through high-tech traps inside the automated facility.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBcMjk6GBmFbS8N1m5vNZcbxQI7-SaOK_3t23nSVOHkYuRz5oekq2sfXu8wrw1-Y8Kr7csKzTpJmRHwlliiPT5bLkKmffV65TN1hylGWxs7PdtZyxz61jlQHuwxwPpMbC7I-3oNYgDaPotu2cNt3S1u0GYoJoXxkZLnzh4njqyqo8O3mPCQsGhc7jnZC7eME-4LycW3VeHELXbX8yj6N-8Vbe6vc89pFGUDqLBtFM3TTm1cb67B-lyeLnmqIjnFaXh6LN118zLAe-s',
    rating: 9.1,
    tags: ['HDR', 'DOLBY SURROUND'],
    category: 'top_rated',
    releaseYear: '2023',
    duration: '1h 50m',
    genres: ['Sci-Fi', 'Thriller', 'Horror'],
    director: 'Claire Sterling',
    cast: ['Rebecca Hall', 'John Boyega', 'Paul Bettany'],
  },
  {
    id: 'deep-blue',
    title: 'Deep Blue',
    tagline: 'Life of the silent world, illuminated.',
    description: 'A spectacular, vibrant underwater adventure nature documentary that captures the mesmerizing beauty of bioluminescent reefs and undiscovered exotic creatures of the deep oceanic trenches. Using custom pressure-proof lighting systems, this film uncovers active alien-like micro-universes.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEYisJcomBw6DehokorBl86U31LMxGy1Mx7maFOp0n7z9TQwgZMCqseyMbSea8Y7TOsJ0QBSgzobKAAOxVn8bDFiHkXbyfEq7FxBmKbLGRCS8fyoGjBgL2ID4hsF-uCUq6iTTV9MkynB6HuCxrB3tCDMGfpm5evgI1-svczTGY7bGXDG8xoPh6GRUNH7F_tF-x6KnXG3eij0fahMWEg4UUd8nVBZXZKIvvhz0m1HWxV83m8Z2DRFobrkVxgSBaCAF3Mh46mWlWli4',
    rating: 9.3,
    tags: ['4K ULTRA HD', 'HIGH BITRATE', 'G'],
    category: 'top_rated',
    releaseYear: '2022',
    duration: '1h 42m',
    genres: ['Documentary', 'Adventure', 'Nature'],
    director: 'David Attenborough',
    cast: ['Narrated by David Attenborough'],
  },
  {
    id: 'polygon-peak',
    title: 'Polygon Peak',
    tagline: 'Climbing the mountains of the mental grid.',
    description: 'A minimalist abstract vaporwave landscape adventure. A lone wanderer climbs grid-like modular geometric peaks underneath a burning purple cybernetic sun, unlocking retro soundtracks and testing the borders of simulation-based realities.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCpvUEZ7yDCzQHiyNm2762V1u6Aatovi0aI1dnXZmZVZibJhzbqWVBLKnm9azX8VkEZGdVgeBQQhBtSmjdxFyLUKfvt_mXpA_FEyyTE4_klLSoGTG10qqSDvP0WoAv_zhlxQZZmSoFF5sy1ZsyjrMJ3be5N16Ef4B86_QiQwPEs-4C3iwl-eQ1hGktQ0PPxjJlzwaijRQ5w0psanPTJATmq1aBfwnIgoqNCncI7U1SNdoE9dDnc81WUrLhl1bREC7eWa99Q6y8K1D0',
    rating: 8.5,
    tags: ['HD', 'SYNTH_WAVE', 'PG'],
    category: 'top_rated',
    releaseYear: '2023',
    duration: '1h 24m',
    genres: ['Abstract', 'Visual', 'Electronic'],
    director: 'Vector Kid',
    cast: ['Music by Com Truise'],
  },
  {
    id: 'velocity',
    title: 'Velocity',
    tagline: 'No traffic. No limits. No turning back.',
    description: 'An adrenaline-fueled, high-speed cinema experience tracking a sleek silver titanium hypercar shredding the desert asphalt at glowing sunset. Utilizing revolutionary drone cinematography and high-frequency audio recording of roaring engines.',
    type: 'movie',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCo9uVgv75Z1VNm-yjiHBaK6_FUMGHIJn9Rt1XxOFwq-IR4Ee7A96s44fhlykhvgILQfLr1ImeNqKzkK0go7Uxr6lRr6xDeFFw_JER22_wL-VSpMl7mQUzy8bXJKmqFtrnaYBBLeOvrBEM9pCOc5dRPHTSRPQZe60GG-y0FZ9P0V5QQ9_y__AgCOfs_yMvsGy83GlKtni33L-akIzm5DXHJG5psudGVvgAbScAtkt2xYbpB7SB67VfZb_l52sVfRX_GoerOSk-I9U',
    rating: 8.8,
    tags: ['4K HDR', 'DOLBY', 'PG-13'],
    category: 'top_rated',
    releaseYear: '2024',
    duration: '1h 52m',
    genres: ['Action', 'Sports', 'Thriller'],
    director: 'Justin Lin',
    cast: ['Jason Statham', 'Michelle Rodriguez', 'Mads Mikkelsen'],
  }
];

export const PROFILE_AVATAR = 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2J7mVRU29ptmUUitBF3ohN5I53VR2_d_dmfT4rSRDxOUZMcnPoflJijUc_fkkneQZoO-MovRZkCRLvsCGSjzfZrE41cuCj1N_hnrc-I41Pq3QBtJK1faOIaKYKiqTMFBH6VbR0grF7peeZbvHRCkWH3IXfQtV-G-6B84tnCrNLZoYJlQA26LciP6k5eAadrPgx169Tqy6Q8nYg-ngGMLE3QHDZYFzpjzXkt0hlbBvl50WKltoUD3rjj8BaHGa7g3pwKZyiQKlv8E';
